### ISSUE TITLE
Stock MCTS with UCT leaks hidden information (aka cheats)

### ISSUE THREAD

**Issue by Meerkov** [hlynurd/open-mtg#4]
Hi, it looks like this algorithm performs a MCTS rollout on a game with hidden information. This leaks information back up the tree about the hidden state of the decks and hands. Thus the AI is actually able to play as if there was no hidden information in the game, which is probably not what you intended.

**Comment by hlynurd** [comment]
Thank you for the feedback. All hidden information is randomized before each rollout.

**Comment by Meerkov** [comment]
Hi, yes, you can randomize, but you can't do it the way you are doing. See the other issues I filed.
